name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
